name: 'Compute BSP matrix - no toolchain'
description: 'Prepares the build environment. no toolchain'
outputs:
  matrix:
    description: "Build matrix"
    value: ${{ steps.compute-matrix-no-tc.outputs.matrix }}
runs:
  using: "composite"
  steps:
    - run: sudo apt-get install -y jq
      shell: bash
    - id: compute-matrix-no-tc
      shell: bash
      run: |
        matrix_json=$(cat crates.json | jq -Mr -c '{ "bsp": (.boards | keys ) }')
        echo "::set-output name=matrix::${matrix_json}"
