name: Clippy BSP & HAL code
on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix:
        description: "Build matrix"
        value: ${{ steps.compute-matrix.outputs.matrix }}
    using: "composite"
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - run: sudo apt-get install -y jq
      shell: bash
    - id: set-matrix
      shell: bash
      run: |
        matrix_json=$(cat crates.json | jq -Mr -c '{ "bsp": (.boards | keys ) }')
        echo "::set-output name=matrix::${matrix_json}"

  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: setup
    strategy:
      matrix: ${{fromJson(needs.setup.outputs.matrix)}}
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Install Rust (thumbv6m)
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
        target: thumbv6m-none-eabi
        components: clippy
    - name: Install Rust (thumbv7em)
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
        target: thumbv7em-none-eabihf
        components: clippy

    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Clippy {{ matrix.bsp }}
        args: --all-features --manifest-path=boards/${{ matrix.bsp }}/Cargo.toml
